name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: wasm32-unknown-unknown
      - run: cargo fmt --all -- --check
      - run: cargo clippy --locked --all-features --workspace --all-targets -- -D warnings
      - run: cargo clippy --locked --target wasm32-unknown-unknown --all-features --all-targets -- -D warnings
      - run: cargo doc --locked --all-features --no-deps
        env:
          RUSTDOCFLAGS: -D warnings

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, '1.85.0']
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: wasm32-unknown-unknown
      - run: cargo +${{ matrix.toolchain }} test --locked
      - run: cargo +${{ matrix.toolchain }} test --locked --all-features
      - run: cargo +${{ matrix.toolchain }} check --locked --target wasm32-unknown-unknown --all-features --all-targets

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo install wasm-pack --locked
      - uses: browser-actions/setup-firefox@v1
      - run: wasm-pack test --firefox --headless -- --locked --all-features --lib
      - run: wasm-pack build --release --target nodejs -- --locked
